"""initial schema

Revision ID: 1db90b61a654
Revises:
Create Date: 2026-08-20 03:28:05.943546
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1db90b61a654"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=80), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("analysis_version", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_target_id"), "feedback", ["target_id"], unique=False)
    op.create_index(op.f("ix_feedback_target_type"), "feedback", ["target_type"], unique=False)
    op.create_table(
        "industry",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("scheme", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("parent_id", sa.String(length=80), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["industry.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scheme", "code", name="uq_industry_scheme_code"),
    )
    op.create_index(op.f("ix_industry_name"), "industry", ["name"], unique=False)
    op.create_table(
        "pipeline_job",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("job_type", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_pipeline_job_job_type"), "pipeline_job", ["job_type"], unique=False)
    op.create_index(op.f("ix_pipeline_job_status"), "pipeline_job", ["status"], unique=False)
    op.create_table(
        "source",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("owner", sa.String(length=240), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("tier", sa.String(length=8), nullable=False),
        sa.Column("official", sa.Boolean(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("entry_url", sa.Text(), nullable=False),
        sa.Column("fallback_url", sa.Text(), nullable=True),
        sa.Column("schedule", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("content_policy", sa.String(length=40), nullable=False),
        sa.Column("compliance_notes", sa.Text(), nullable=False),
        sa.Column("contact_owner", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_enabled"), "source", ["enabled"], unique=False)
    op.create_index(op.f("ix_source_language"), "source", ["language"], unique=False)
    op.create_index(op.f("ix_source_region"), "source", ["region"], unique=False)
    op.create_index(op.f("ix_source_tier"), "source", ["tier"], unique=False)
    op.create_table(
        "article",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("origin_url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=240), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_timezone", sa.String(length=80), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("independence_group", sa.String(length=80), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "canonical_url", name="uq_article_source_url"),
    )
    op.create_index("ix_article_content_hash", "article", ["content_hash"], unique=False)
    op.create_index(
        op.f("ix_article_independence_group"), "article", ["independence_group"], unique=False
    )
    op.create_index(op.f("ix_article_language"), "article", ["language"], unique=False)
    op.create_index(op.f("ix_article_published_at"), "article", ["published_at"], unique=False)
    op.create_index(op.f("ix_article_source_id"), "article", ["source_id"], unique=False)
    op.create_table(
        "entity",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=24), nullable=False),
        sa.Column("canonical_name", sa.String(length=240), nullable=False),
        sa.Column("country", sa.String(length=40), nullable=True),
        sa.Column("parent_id", sa.String(length=80), nullable=True),
        sa.Column("identifiers_json", sa.JSON(), nullable=False),
        sa.Column("industry_id", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(["industry_id"], ["industry.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["entity.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entity_canonical_name"), "entity", ["canonical_name"], unique=False)
    op.create_table(
        "source_run",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_run_source_id"), "source_run", ["source_id"], unique=False)
    op.create_index(op.f("ix_source_run_status"), "source_run", ["status"], unique=False)
    op.create_table(
        "article_version",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("article_id", sa.String(length=40), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("body_excerpt", sa.Text(), nullable=False),
        sa.Column("body_ref", sa.Text(), nullable=True),
        sa.Column("body_permitted", sa.Boolean(), nullable=False),
        sa.Column("version_hash", sa.String(length=64), nullable=False),
        sa.Column("parse_diagnostics", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["article.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "version_hash", name="uq_article_version_hash"),
    )
    op.create_index(
        op.f("ix_article_version_article_id"), "article_version", ["article_id"], unique=False
    )
    op.create_table(
        "entity_alias",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=False),
        sa.Column("alias", sa.String(length=240), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("alias_type", sa.String(length=24), nullable=False),
        sa.Column("negative", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "alias", name="uq_entity_alias"),
    )
    op.create_index(op.f("ix_entity_alias_alias"), "entity_alias", ["alias"], unique=False)
    op.create_index(op.f("ix_entity_alias_entity_id"), "entity_alias", ["entity_id"], unique=False)
    op.create_table(
        "event_cluster",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("representative_article_id", sa.String(length=40), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["representative_article_id"], ["article.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_cluster_last_seen"), "event_cluster", ["last_seen"], unique=False
    )
    op.create_index(op.f("ix_event_cluster_state"), "event_cluster", ["state"], unique=False)
    op.create_table(
        "syndication_link",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("from_article_id", sa.String(length=40), nullable=False),
        sa.Column("to_article_id", sa.String(length=40), nullable=False),
        sa.Column("relation", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["from_article_id"], ["article.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_article_id"], ["article.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_article_id", "to_article_id", name="uq_syndication_pair"),
    )
    op.create_table(
        "analysis_run",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=40), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["event_cluster.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analysis_run_event_id"), "analysis_run", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_analysis_run_input_hash"), "analysis_run", ["input_hash"], unique=False
    )
    op.create_index(op.f("ix_analysis_run_stage"), "analysis_run", ["stage"], unique=False)
    op.create_table(
        "event_article",
        sa.Column("event_id", sa.String(length=40), nullable=False),
        sa.Column("article_id", sa.String(length=40), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("is_representative", sa.Boolean(), nullable=False),
        sa.Column("added_by", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["article.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["event_cluster.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "article_id"),
    )
    op.create_table(
        "report",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=40), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("artifact_ref", sa.Text(), nullable=True),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column("content_html", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_cutoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["event_cluster.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "version", name="uq_report_event_version"),
    )
    op.create_index(op.f("ix_report_event_id"), "report", ["event_id"], unique=False)
    op.create_index(op.f("ix_report_input_hash"), "report", ["input_hash"], unique=False)
    op.create_table(
        "claim",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=40), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=40), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("subject", sa.String(length=240), nullable=True),
        sa.Column("predicate", sa.String(length=120), nullable=True),
        sa.Column("object", sa.Text(), nullable=True),
        sa.Column("claim_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sa.String(length=40), nullable=True),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_run.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["event_cluster.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claim_event_id"), "claim", ["event_id"], unique=False)
    op.create_index(op.f("ix_claim_is_current"), "claim", ["is_current"], unique=False)
    op.create_table(
        "company_impact",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("relevance", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("strength", sa.String(length=16), nullable=False),
        sa.Column("horizon", sa.String(length=24), nullable=False),
        sa.Column("mechanism", sa.String(length=32), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_run.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["event_cluster.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "entity_id", name="uq_event_company"),
    )
    op.create_index(
        op.f("ix_company_impact_entity_id"), "company_impact", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_company_impact_event_id"), "company_impact", ["event_id"], unique=False
    )
    op.create_table(
        "industry_impact",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=40), nullable=False),
        sa.Column("industry_id", sa.String(length=80), nullable=False),
        sa.Column("relevance", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("strength", sa.String(length=16), nullable=False),
        sa.Column("horizon", sa.String(length=24), nullable=False),
        sa.Column("mechanism", sa.String(length=32), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_run.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["event_cluster.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["industry_id"], ["industry.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "industry_id", name="uq_event_industry"),
    )
    op.create_index(
        op.f("ix_industry_impact_event_id"), "industry_impact", ["event_id"], unique=False
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("report_id", sa.String(length=40), nullable=False),
        sa.Column("channel", sa.String(length=24), nullable=False),
        sa.Column("target_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["report_id"], ["report.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_notification_report_id"), "notification", ["report_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("claim_id", sa.String(length=40), nullable=False),
        sa.Column("article_id", sa.String(length=40), nullable=False),
        sa.Column("source_tier", sa.String(length=8), nullable=False),
        sa.Column("stance", sa.String(length=24), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("independence_group", sa.String(length=80), nullable=False),
        sa.Column("independence_known", sa.Boolean(), nullable=False),
        sa.Column("quality", sa.String(length=16), nullable=False),
        sa.Column("primary_material", sa.Boolean(), nullable=False),
        sa.Column("directly_observed", sa.Boolean(), nullable=False),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["article.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["claim_id"], ["claim.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_article_id"), "evidence", ["article_id"], unique=False)
    op.create_index(op.f("ix_evidence_claim_id"), "evidence", ["claim_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_independence_group"), "evidence", ["independence_group"], unique=False
    )
    op.create_table(
        "verification",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("claim_id", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_run.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["claim_id"], ["claim.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verification_claim_id"), "verification", ["claim_id"], unique=False)
    op.create_index(op.f("ix_verification_status"), "verification", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_status"), table_name="verification")
    op.drop_index(op.f("ix_verification_claim_id"), table_name="verification")
    op.drop_table("verification")
    op.drop_index(op.f("ix_evidence_independence_group"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_claim_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_article_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_notification_report_id"), table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("ix_industry_impact_event_id"), table_name="industry_impact")
    op.drop_table("industry_impact")
    op.drop_index(op.f("ix_company_impact_event_id"), table_name="company_impact")
    op.drop_index(op.f("ix_company_impact_entity_id"), table_name="company_impact")
    op.drop_table("company_impact")
    op.drop_index(op.f("ix_claim_is_current"), table_name="claim")
    op.drop_index(op.f("ix_claim_event_id"), table_name="claim")
    op.drop_table("claim")
    op.drop_index(op.f("ix_report_input_hash"), table_name="report")
    op.drop_index(op.f("ix_report_event_id"), table_name="report")
    op.drop_table("report")
    op.drop_table("event_article")
    op.drop_index(op.f("ix_analysis_run_stage"), table_name="analysis_run")
    op.drop_index(op.f("ix_analysis_run_input_hash"), table_name="analysis_run")
    op.drop_index(op.f("ix_analysis_run_event_id"), table_name="analysis_run")
    op.drop_table("analysis_run")
    op.drop_table("syndication_link")
    op.drop_index(op.f("ix_event_cluster_state"), table_name="event_cluster")
    op.drop_index(op.f("ix_event_cluster_last_seen"), table_name="event_cluster")
    op.drop_table("event_cluster")
    op.drop_index(op.f("ix_entity_alias_entity_id"), table_name="entity_alias")
    op.drop_index(op.f("ix_entity_alias_alias"), table_name="entity_alias")
    op.drop_table("entity_alias")
    op.drop_index(op.f("ix_article_version_article_id"), table_name="article_version")
    op.drop_table("article_version")
    op.drop_index(op.f("ix_source_run_status"), table_name="source_run")
    op.drop_index(op.f("ix_source_run_source_id"), table_name="source_run")
    op.drop_table("source_run")
    op.drop_index(op.f("ix_entity_canonical_name"), table_name="entity")
    op.drop_table("entity")
    op.drop_index(op.f("ix_article_source_id"), table_name="article")
    op.drop_index(op.f("ix_article_published_at"), table_name="article")
    op.drop_index(op.f("ix_article_language"), table_name="article")
    op.drop_index(op.f("ix_article_independence_group"), table_name="article")
    op.drop_index("ix_article_content_hash", table_name="article")
    op.drop_table("article")
    op.drop_index(op.f("ix_source_tier"), table_name="source")
    op.drop_index(op.f("ix_source_region"), table_name="source")
    op.drop_index(op.f("ix_source_language"), table_name="source")
    op.drop_index(op.f("ix_source_enabled"), table_name="source")
    op.drop_table("source")
    op.drop_index(op.f("ix_pipeline_job_status"), table_name="pipeline_job")
    op.drop_index(op.f("ix_pipeline_job_job_type"), table_name="pipeline_job")
    op.drop_table("pipeline_job")
    op.drop_index(op.f("ix_industry_name"), table_name="industry")
    op.drop_table("industry")
    op.drop_index(op.f("ix_feedback_target_type"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_target_id"), table_name="feedback")
    op.drop_table("feedback")
    # ### end Alembic commands ###
